### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by tekdoodle** [AndreMiras/mdns-lookup#3]
Running mdnslookup and giving existing or non-existing local hostname returns the following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/mdnslookup", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/mdnslookup.py", line 83, in main
    hosts_ip = lookup(hosts)
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/mdnslookup.py", line 28, in lookup
    sock.bind((UDP_IP, UDP_PORT))
OSError: [Errno 48] Address already in use

OS version: macOS Big Sur version 11.6.8

python3 --version 
Python 3.10.7

pip3 --version   
pip 22.2.2 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)

pip3 list
Package     Version
----------- --------
dpkt        1.9.8
mdns-lookup 20200613
pip         22.2.2
setuptools  63.2.0

**Comment by AndreMiras** [comment]
Mostlikely macOS already has a service binding on this port to do the exact same thing, refs https://support.apple.com/en-us/HT202944
Maybe we could adapt or make a dedicated package that leverage the service already available on mac.
But my guess is that it shouldn't be needed as macOS would resolve it for you directly e.g. if you ping the address

**Comment by tekdoodle** [comment]
You are correct. Apple mdns service is running on UDP port 5353. I just found there is a tool called dns-sd available on macOS to query mdns.

**Comment by AndreMiras** [comment]
Sweet thanks for sharing, I'm closing that one then
